// Code generated by "stringer -type=Origin -output=model_string.go"; DO NOT EDIT.

package geo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OriginActivity-0]
	_ = x[OriginPlanned-1]
	_ = x[OriginUnknown-2]
}

const _Origin_name = "OriginActivityOriginPlannedOriginUnknown"

var _Origin_index = [...]uint8{0, 14, 27, 40}

func (i Origin) String() string {
	if i < 0 || i >= Origin(len(_Origin_index)-1) {
		return "Origin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Origin_name[_Origin_index[i]:_Origin_index[i+1]]
}
