before:
  hooks:
    - task test
builds:
  - env:
      - CGO_ENABLED=0
      - PKG={{.ModulePath}}/version
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/gravl
    ldflags:
      - -s -w -X {{.Env.PKG}}.BuildVersion={{.Version}} -X {{.Env.PKG}}.BuildCommit={{.ShortCommit}} -X {{.Env.PKG}}.BuildTime={{.Date}} -X {{.Env.PKG}}.BuildBuilder=goreleaser
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge pull request"
announce:
  skip: "true"

brews:
  - name: gravl
    homepage: https://github.com/bzimmer/gravl
    description: Command line clients for activity-related services
    license: MIT
    commit_author:
      name: bzimmer
      email: bzimmer@ziclix.com
    tap:
      owner: bzimmer
      name: homebrew-tap
    skip_upload: auto
    install: bin.install "gravl"
