steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'VERSION=$SHORT_SHA', '-t', 'gcr.io/${PROJECT_ID}/wta:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/wta:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'wta', '--image', 'gcr.io/${PROJECT_ID}/wta:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed']
images:
- 'gcr.io/${PROJECT_ID}/wta:$COMMIT_SHA'
