# https://taskfile.dev

version: '3'

vars:
  APP:
    sh: basename $PWD
  DIST: dist
  MODE: dev
  GO_PACKAGES:
    sh: go list ./...
  VERSION:
    sh: git rev-parse --short HEAD
  LDFLAGS:
    -ldflags "-X github.com/bzimmer/wta/pkg/wta.BuildVersion={{.VERSION}}"

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build the application
    sources:
      - '**/*.go'
    cmds:
      - 'go build {{.LDFLAGS}} -o {{.DIST}}/{{.APP}} cmd/{{.APP}}/*.go'

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - '{{.DIST}}/{{.APP}} -color serve'

  lint:
    desc: Runs golint
    cmds:
      - golint {{catLines .GO_PACKAGES}}

  vet:
    desc: Runs golint
    cmds:
      - go vet {{catLines .GO_PACKAGES}}

  test:
    desc: Run all tests
    cmds:
      - mkdir -p {{.DIST}}
      - go test -covermode count -coverprofile {{.DIST}}/coverage.txt {{catLines .GO_PACKAGES}}
  
  cover:
    desc: Visualize test coverage
    deps: [test]
    cmds:
      - go tool cover -html={{.DIST}}/coverage.txt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.DIST}}
      - rm -rf .task

  install:
    desc: Install {{.APP}}
    deps: [test]
    cmds:
      - cd cmd/{{.APP}} && go install {{.LDFLAGS}}

  docker:
    desc: Create a docker image for {{.APP}}
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} -t {{.APP}} .

  docker-run:
    desc: Run the docker container for {{.APP}}
    deps: [docker]
    cmds:
      - docker container run -p8080:8080 {{.APP}}
