#!/bin/bash
set -e

num="${NUM_ACTIVITIES:-50}"

function _jq() {
    if ! command -v jq &> /dev/null
    then
        cat "$@"
        exit
    fi
    jq -sc ".[]" "$@"
}

# If no activity is provided display the most recent rides
if [[ $# -eq 0 ]]
then
    gravl -c --timeout 1m strava activities -N $num -f ".Type == 'VirtualRide'" -B ".ID, .Name, .StartDateLocal, .Distance.Miles()" | _jq
    exit 0
fi

for arg in "$@"
do
    gravl strava export -o -T "$arg.fit" -F fit $arg
    gravl cyclinganalytics upload -p "$arg.fit"
    rm -f "$arg.fit"
done
