// Code generated by "stringer -type=AlertLevel -linecomment -output model_string.go"; DO NOT EDIT.

package visualcrossing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlertLevelNone-0]
	_ = x[AlertLevelSummary-1]
	_ = x[AlertLevelDetail-2]
}

const _AlertLevel_name = "nonesummarydetail"

var _AlertLevel_index = [...]uint8{0, 4, 11, 17}

func (i AlertLevel) String() string {
	if i < 0 || i >= AlertLevel(len(_AlertLevel_index)-1) {
		return "AlertLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AlertLevel_name[_AlertLevel_index[i]:_AlertLevel_index[i+1]]
}
