// Code generated by "stringer -type=Units -output=model_string.go"; DO NOT EDIT.

package openweather

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnitsMetric-0]
	_ = x[UnitsImperial-1]
	_ = x[UnitsStandard-2]
}

const _Units_name = "UnitsMetricUnitsImperialUnitsStandard"

var _Units_index = [...]uint8{0, 11, 24, 37}

func (i Units) String() string {
	if i < 0 || i >= Units(len(_Units_index)-1) {
		return "Units(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Units_name[_Units_index[i]:_Units_index[i+1]]
}
