// Code generated by "stringer -type=Encoding -linecomment -output=encoding_string.go"; DO NOT EDIT.

package encoding

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EncodingNative-0]
	_ = x[EncodingXML-1]
	_ = x[EncodingJSON-2]
	_ = x[EncodingGeoJSON-3]
	_ = x[EncodingGPX-4]
	_ = x[EncodingSpew-5]
}

const _Encoding_name = "nativexmljsongeojsongpxspew"

var _Encoding_index = [...]uint8{0, 6, 9, 13, 20, 23, 27}

func (i Encoding) String() string {
	if i < 0 || i >= Encoding(len(_Encoding_index)-1) {
		return "Encoding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Encoding_name[_Encoding_index[i]:_Encoding_index[i+1]]
}
