// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strava

// GroupByIntActivityPtr returns a mapping of int to []*Activity based on the return
// value of function `f`
//
// Example:
// groups := GroupByIntActivityPtr(func(val *Activity) int {
// return IntIsh
//   }, vals)
func GroupByIntActivityPtr(f func(act *Activity) int, coll []*Activity) map[int][]*Activity {
	res := make(map[int][]*Activity)
	EveryActivityPtr(func(act *Activity) bool {
		key := f(act)
		res[key] = append(res[key], act)
		return true
	}, coll)
	return res
}

// GroupByIntActivity returns a mapping of int to []Activity based on the return
// value of function `f`
//
// Example:
// groups := GroupByIntActivity(func(val *Activity) int {
// return IntIsh
//   }, vals)
func GroupByIntActivity(f func(act Activity) int, coll []Activity) map[int][]Activity {
	res := make(map[int][]Activity)
	EveryActivity(func(act Activity) bool {
		key := f(act)
		res[key] = append(res[key], act)
		return true
	}, coll)
	return res
}
