// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strava

// MapActivityPtr iterates over the slice of Activity returning a new slice after applying the function
func MapActivityPtr(f func(*Activity) *Activity, coll []*Activity) []*Activity {
	if f == nil {
		return []*Activity{}
	}
	w := make([]*Activity, len(coll))
	for i, v := range coll {
		w[i] = f(v)
	}
	return w
}

// func MapActivity(f func(Activity) Activity, coll []Activity) []Activity {
// 	if f == nil {
// return []Activity{}
// 	}
// w := make([]Activity, len(coll))
// 	for i, v := range coll {
// 		w[i] = f(v)
// 	}
// 	return w
