// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strava

// EveryActivityPtr iterates all Activity
func EveryActivityPtr(f func(*Activity) bool, coll []*Activity) bool {
	if f == nil || len(coll) == 0 {
		return false
	}
	for _, v := range coll {
		if !f(v) {
			return false
		}
	}
	return true
}

// func EveryActivity(f func(Activity) bool, coll []Activity) bool {
// 	if f == nil || len(coll) == 0 {
// 		return false
// 	}
// 	for _, v := range coll {
// 		if !f(v) {
// 			return false
// 		}
// 	}
// 	return true
