// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strava

func MapActivity(f func(Activity) Activity, coll []Activity) []Activity {
	if f == nil {
		return []Activity{}
	}
	w := make([]Activity, len(coll))
	for i, v := range coll {
		w[i] = f(v)
	}
	return w
}

func MapActivityPtr(f func(*Activity) *Activity, coll []*Activity) []*Activity {
	if f == nil {
		return []*Activity{}
	}
	w := make([]*Activity, len(coll))
	for i, v := range coll {
		w[i] = f(v)
	}
	return w
}
