// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strava

func FilterActivity(f func(Activity) bool, coll []Activity) []Activity {
	if f == nil {
		return []Activity{}
	}
	var w []Activity
	for _, v := range coll {
		if f(v) {
			w = append(w, v)
		}
	}
	return w
}

func FilterActivityPtr(f func(*Activity) bool, coll []*Activity) []*Activity {
	if f == nil {
		return []*Activity{}
	}
	var w []*Activity
	for _, v := range coll {
		if f(v) {
			w = append(w, v)
		}
	}
	return w
}
